[url]
ISO = https://minerva-archive.org/browse/Redump/Sony%20-%20PlayStation%203/
KEY = https://minerva-archive.org/browse/Redump/Sony%20-%20PlayStation%203%20-%20Disc%20Keys%20TXT/

[Download]
# Downloaded Game list fileName 
LIST_FILES_JSON_NAME = listPS3Titles.json 

# Download ISO file using alternative torrent client
EXTERNAL_ISO = 0 
# Download KEY file using alternative torrent client
EXTERNAL_KEY = 0 


[folder]
TMP_FOLDER_NAME = tmp
TMP_ISO_FOLDER_NAME = iso_files
TMP_KEY_FOLDER_NAME = key_files

